### ISSUE TITLE
"You may also enjoy" section and social media buttons

### ISSUE THREAD

**Issue by mechalord7** [mechalord7/mechalord7.github.io#4]
Add Coming Soon! to you may also enjoy section and edit functionality of social media buttons

**Comment by 99ashutosh** [comment]
The "you may also enjoy" section depends on the number of posts you have. As that is one right now, it won't show anything

**Comment by 99ashutosh** [comment]
Also note that those social buttons are sharing buttons, they will share the page with the user.

Just like normal share

**Comment by mechalord7** [comment]
okayy
